### Get all users
GET {{baseUrl}}/users

### Get user by id
# @prompt userId
GET {{baseUrl}}/users/{{userId}}

### Create user
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "",
    "email": ""
}
